"""empty message

Revision ID: 3f5fd312c67d
Revises: fb160ec2556b
Create Date: 2023-10-25 16:06:28.412632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f5fd312c67d'
down_revision = 'fb160ec2556b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=3000), nullable=False),
    sa.Column('category', sa.String(length=300), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
