"""empty message

Revision ID: 4eeb584c135c
Revises: c5636f5cde21
Create Date: 2023-10-15 23:40:37.620534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eeb584c135c'
down_revision = 'c5636f5cde21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ship_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipDetail_id', sa.Integer(), nullable=False))
        batch_op.drop_column('address_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ship_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_column('shipDetail_id')

    # ### end Alembic commands ###
