"""empty message

Revision ID: d86196644a64
Revises: 02cbaad58f6c
Create Date: 2023-10-15 15:52:09.871552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd86196644a64'
down_revision = '02cbaad58f6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('rut_numbers', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('first_name', sa.String(length=300), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=300), nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('terms_conditions', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('register_date', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['rut_numbers'])
        batch_op.create_unique_constraint(None, ['phone_number'])
        batch_op.drop_column('id_user')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=300), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('id_user', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('register_date')
        batch_op.drop_column('terms_conditions')
        batch_op.drop_column('password')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')
        batch_op.drop_column('rut_numbers')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
